### ISSUE TITLE
Only already added issues and PRs are affected by automation? (except `new_*` of course)

### ISSUE THREAD

**Issue by janpio** [philschatz/project-bot#18]
Did I understand correctly that only issues or pull requests that are already part of the project board are affected by project-bot rules? 

Exceptions of course are the 2 rules to add issues and PRs to the borad in the first place, `new_issue` and `new_pullrequest`.

**Comment by philschatz** [comment]
Yes that is correct. `new_issue` and `new_pullrequest` are the only rules that add Issues/PullRequests to the board.

**Comment by janpio** [comment]
That got me thinking about this as a possible source for problems or unintended behavior: https://github.com/philschatz/project-bot/issues/24
