### ISSUE TITLE
Add Issue/PR the Project, when assigned to a milestone?

### ISSUE THREAD

**Issue by GaryJones** [philschatz/project-bot#26]
Would it be possible to add functionality, such that Issues and PRs assigned to X milestone get put in X project (and then existing rules could presumably automatically put that in a particular column.)?

Right now, the readme suggests that `milestoned_issue` can only be used to _move_ a card once it has already been added.

What we don't want is to require that all issues automatically get added to a project.

**Comment by janpio** [comment]
Did I understand correctly that you are looking for a way to add issues to a project board when they are added to a milestone?

If so, this is definitely not possible right now, the only way to _add_ issues is via `new_issue` when they are created. 

In theory it would be possible to create an "add issue to board when it is added to milestone `x.y`" of course - but that would probably not really match the current naming.

Can you tell a bit more about the use case behind that? Do you want one project board per milestone?

**Comment by GaryJones** [comment]
> Did I understand correctly that you are looking for a way to add issues to a project board when they are added to a milestone?

That is correct.

> Do you want one project board per milestone?

Yes. Right now, the projects are milestone-based - one project board for 2.7, one for 2.8, one for 2.9, etc.

**Comment by janpio** [comment]
Can you think of a name for the "trigger" that would somehow match the current scheme? This might be the biggest hurdle right now.

**Comment by GaryJones** [comment]
I've not looked at the logic, but could `milestoned_issue` be re-used? i.e. if the board doesn't yet exist on a board, then add it and "move" it to the correct column?

(Aside: there's no `miletoned_pullrequest`?)

If not, maybe `milestoned_issue_add` or similar variant?

**Comment by janpio** [comment]
Reusing doesn't work, something has to tell the code that it should _add_ an issue. So `add_milestoned_issue` might be a good idea.

But: This of course opens the possibility of further "triggers" to add an issue or PR to a board. Any other useful ones?

> (Aside: there's no milestoned_pullrequest?)

Seems so. Best create an issue for it.

**Comment by munnerz** [comment]
+1 for this - I'd love a way to automatically add a PR or Issue to a project when it is added to a milestone, and the inverse, it'd be great to *remove* it from the project automatically when it is removed from that milestone.

Something like:

```
milestoned_issue v0.6
demilestoned_issue v0.6

milestoned_pullrequest v0.6
demilestoned_pullrequest v0.6

// The old behaviour of the commands without an arg could be retained.
// This then matches *all* issues/PRs as they are added to any milestone.
milestoned_issue
milestoned_pullrequest
```

**Comment by janpio** [comment]
> // The old behaviour of the commands without an arg could be retained.

Note that the current implementation only _moves_ already existing items and does not _add_ them to a board. That's why implementing this would be a major new feature for the bot and would probably require a rework on the naming of stuff.

**Comment by gannebamm** [comment]
I would like this feature

**Comment by sleepylee** [comment]
+1
