### ISSUE TITLE
[Issue] - Automation rules must appear at the top or bottom of the column in order to run.

### ISSUE THREAD

**Issue by KerryPoe-asti** [philschatz/project-bot#36]
The automation rules are not running unless the **Automation Rules** card is located at the top or bottom of the list. If the card is located between two or more issues the automation rule is not applied.

**Comment by alexfornuto** [comment]
I'm by no means a dev, but based on the comment [here](https://github.com/philschatz/project-bot/blob/master/src/index.js#L22) and a surface-scan of the code below it, I would venture that this is not so much a bug as an undocumented requirement. I'll submit a PR to update the README.
