### ISSUE TITLE
[Issue] - New Card trigger not working.

### ISSUE THREAD

**Issue by alexfornuto** [philschatz/project-bot#43]
The trigger card on my [project](https://github.com/pantheon-systems/documentation/projects/14) is formatted as:

```
###### Automation Rules

<!-- Documentation: https://github.com/philschatz/project-bot -->

- `new_issue` **documentation**
```

It's at the bottom of the **Inbox** column. New issues to the `documentation` repo  are not added to the project.

**Comment by matomesc** [comment]
Same problem here. It only works when the automation card is at the very top. Once the first issue card gets added and the automation card gets pushed down it doesn't work anymore.

**Comment by sblatz** [comment]
This problem seems to also be happening with `closed_issue` trigger too 😕

Would love to see a fix for this as it's one of our main use cases!

**Comment by m90** [comment]
We are also running into this, the automation card is at the very bottom of the column and looks like this:

```
###### Automation Rules

<!-- Documentation: https://github.com/philschatz/project-bot -->

- `new_issue` **our-repo-name**
```

yet nothing at all happens.

**Comment by arbolitoloco** [comment]
Also running into this, even when card is at top bottom (seems like position doesn't really matter)

**Comment by sblatz** [comment]
For anyone who may still be having this problem, our issue was that we were using more than 10 columns in our project board. The bot only automates the **first 10 columns** as seen [here](https://github.com/philschatz/project-bot/blob/master/src/index.js#L26) in the code. If you want more than 10 I think you'll need to fork your own project :\

**Comment by philschatz** [comment]
Thank you @sblatz for pointing out that at least some of the problems arose from boards having more than 10 columns. #67 should fix that limitation and should be fixed soon after the Pull Request is merged.

**Comment by sblatz** [comment]
@philschatz thanks so much for submitted that fix 😄

**Comment by alexfornuto** [comment]
This issue is resolved, thanks!
