### ISSUE TITLE
[BUG] automation seems to have stopped

### ISSUE THREAD

**Issue by KerryPoe-asti** [philschatz/project-bot#51]
Cards are no longer being moved from column to column when I apply a tag. This has been working without an issue for some time and appears to have stopped either today or within the past two days. 
- My automation cards are at the bottom of my columns
- the tags match the tags specified in the cards

I have not made any changes to the automation rules or tags recently, not sure what's going on here. I do not see a way to message, I hate to add an issue, but can someone help?

**Comment by ondrejbouda** [comment]
I think this is happening since #50 (issue #47) was merged yesterday. @tcely @philschatz 

I tried to reinstall the bot with no effect.

**Comment by ondrejbouda** [comment]
Can I help somehow? I will try to debug the bot locally if I have time.

**Comment by ondrejbouda** [comment]
There is a syntax error in current version of bot. I prepared a fix: #52

I successfully run this version of code locally, rules got applied.

**Comment by tcely** [comment]
Thanks for debugging this. I am sorry to have missed it in my pull request.

**Comment by philschatz** [comment]
Thanks @ondrejbouda for the quick fix!

**Comment by KerryPoe-asti** [comment]
Just tested on my end and it's working again. Thank you for the quick turn around time, you guys rock!
