### ISSUE TITLE
Is this project dead - is there an alternative?

### ISSUE THREAD

**Issue by andersfylling** [philschatz/project-bot#82]
This idea is pretty much what I need. But I have issues when my repo uses multiple projects, and it doesnt seem to handle all types of github events? I wonder if this repo is dead and if someone else have continued the idea or made an alternative. Please let me know!

**Comment by travisjungroth** [comment]
There's this project: https://github.com/alex-page/github-project-automation-plus

**Comment by andersfylling** [comment]
https://github.com/alex-page/github-project-automation-plus/issues/4

It's lacking the core functionality, sadly.

**Comment by celloward** [comment]
Looks like there's a simpler and less cluttered solution using Github Actions:
https://github.com/marketplace/actions/move-labeled-or-milestoned-issue-to-a-specific-project-column

**Comment by andersfylling** [comment]
Seems interesting, I'll soongive it a try.

**Comment by andersfylling** [comment]
It doesn't seem to be that robust. Might try and write my own if I have the time.
